export const UPLOAD_DONE = 'UPLOAD_DONE';
export const SET_IMAGE_PATH = 'SET_IMAGE_PATH'; 


export const SET_IMAGES = 'SET_IMAGES';
export const SET_CATEGORIES = 'SET_CATEGORIES'; 

export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SAVE_USERNAME = 'SAVE_USERNAME';
export const USER_LIKE_START = 'USER_LIKE_START';
export const USER_LIKE_SUCCESS = 'USER_LIKE_SUCCESS';
export const USER_COMMENT_START = 'USER_COMMENT_START';
export const USER_COMMENT_SUCCESS = 'USER_COMMENT_SUCCESS';
export const USER_COMMENT_FAIL = 'USER_COMMENT_FAIL';

export const FETCH_LIKES_COMMENTS_START = 'FETCH_LIKES_COMMENTS_START';
export const FETCH_LIKES_COMMENTS_SUCCESS = 'FETCH_LIKES_COMMENTS_SUCCESS';