export const UPLOAD_DONE = 'UPLOAD_DONE';
export const SET_IMAGE_PATH = 'SET_IMAGE_PATH'; 

export const SET_SEARCHED_VALUE = 'SET_SEARCHED_VALUE';
export const SET_IMAGES_START = 'SET_IMAGES_START';
export const SET_IMAGES = 'SET_IMAGES';
export const SET_CATEGORIES = 'SET_CATEGORIES'; 
export const SET_NEXT_ID = 'SET_NEXT_ID';

export const SET_ORDERS = 'SET_ORDERS';
export const SET_ORDERS_START = 'SET_ORDERS_START';
export const ORDER_DELIVERED = 'ORDER_DELIVERED';
export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SAVE_USERNAME = 'SAVE_USERNAME';
export const USER_LIKE_START = 'USER_LIKE_START';
export const USER_LIKE_SUCCESS = 'USER_LIKE_SUCCESS';
export const USER_COMMENT_START = 'USER_COMMENT_START';
export const USER_COMMENT_SUCCESS = 'USER_COMMENT_SUCCESS';
export const USER_COMMENT_FAIL = 'USER_COMMENT_FAIL';

export const FETCH_LIKES_COMMENTS_START = 'FETCH_LIKES_COMMENTS_START';
export const FETCH_LIKES_COMMENTS_SUCCESS = 'FETCH_LIKES_COMMENTS_SUCCESS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SAVE_DATA_START = 'SAVE_DATA_START';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_FAILURE = 'SAVE_DATA_FAILURE';
export const CLEAR_CART = 'CLEAR_CART';
